### PR TITLE
Update production vs development imports and remove shims with import use

### PR DESCRIPTION
**Pull request by dhedgecock**
Removes AMD shims from vendor folder in favor of `using` syntax:

```
app.import(`${vendor}/prop-types/prop-types${this.env === 'production' ? '.min' : ''}.js`, {
  using: [
    { transformation: 'amd', as: 'prop-types' }
  ]
});
```

Continues to strip out the Component reopen.
Updates docs.

### CODE REVIEW

**Comment by cibernox** [comment]
@DHedgecock if I'm right even if you always include the unminified version, ember-cli will minify it in production anyway, so it won't make any difference. 

Form a theoretical perspective it might even be worse. If `prop-types` was written in ES6 (I don't think it's the case) and the minified version is, as most are, minified ES5 code, that would prevent advanced transpilers like `babili` to ship potentially smaller ES6 code if your app only targets modern browsers. I say theoritical because babili is still slightly less efficient than uglifyjs.

**Comment by rwjblue** [comment]
> if I'm right even if you always include the unminified version, ember-cli will minify it in production anyway, so it won't make any difference.

Confirm, however its actually slightly _worse_ to `app.import` an already minified file.  For some reason `uglify` is **massively** slower when minifying already minified code.

**Comment by dhedgecock** [comment]
Thanks for the help with getting the CLI configs right.

So basically, unless we have a good way to strip out `propTypes` declarations from inside Component definitions we need a set of shims for the prop type validators. I would love to use a babel plugin to strip out the definitions entirely, and then we could not import the library at all in production builds. But that doesn't exist yet 😣.

We could make our own production shims (which we did in the first pass with the `bogus-prop-shim`), but would need to keep them in sync with the prop-types package (See https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js#L34). Honestly it's not that much work to maintain our own shims, but I don't think it's worth it when the library already exports a set of production shims, written by the repo maintainers. Note that while pulling this PR together I noticed that we aren't shimming `arrayOf`, `instanceOf`, `objectOf`, `oneOf`, `oneOfType` or `shape` validators correctly (they are defined as functions and the bogus-prop-shim we have now exports an empty object for PropTypes). Easy to fix, but again, for 0.8KB I'd rather just use the production shims created by the library maintainers.

> if I'm right even if you always include the unminified version, ember-cli will minify it in production anyway, so it won't make any difference.

For the production vs dev imports specifically, the .min file is actually not just a minified version of the library, it's a stripped version of the library that is basically just a set of shims for the validators:
https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js
So it's already had all non-production assets stripped using browserify+envify.

We can't run our own Uglify compress on the dev `prop-types.js` b/c it's already been bundled by Browserify to include all of the development assets and had `process.env.NODE_ENV` references stripped out.

Basically I'm not sure how to handle importing a CommonJS library into CLI without requiring consumers have browserify configured, which I don't think is fair for an addon to require. Is there a way to out of the box import a CommonJS module?


So my thoughts thus far are:

1. I'm believing the `prop-types` index.js can't be imported b/c it is CommonJS, which CLI doesn't support out of the box?
2. Importing the `prop-types.js` doesn't work for production b/c it's already been bundled to include all of the development assets, so trying to strip it with UglifyJS compress options won't work.
3. I'd rather we not maintain a separate set of validator shims when the library already maintains them in the stripped down `prop-types.min.js`.
4. Until someone writes a Babel plugin to strip out the `propTypes` definitions in Components, we need a set of validator shims for production.

You can see the library bundled src files here if interested:
- https://unpkg.com/prop-types@15.5.10/prop-types.js
- https://unpkg.com/prop-types@15.5.10/prop-types.min.js

**Comment by evrowe** [comment]
~~@DHedgecock Thanks for the detailed explanation, that helps add some extra clarity for me.~~

~~While it does sound like `prop-types.min.js` offers some convenient "pre-work" in terms of preparing a file with production-ready exports, I think the original point about whether it's an ES5 or ES6 formatted file will have a lot of bearing on what direction we should take. Given that importing the `.min` file does increase build time due w/ Uglify, we need to very carefully consider/evaluate whether it's the best file to include.~~

~~First off I think we should do some quick baseline testing to determine the real-world speed impact of importing the `.min.js` vs the `.js` file. Given that the `prop-types` library isn't all that large, I suspect the overall impact won't be huge, but it will probably be somewhat noticeable. I do think that continuing to include some flavor of the library for prod (particularly once `getDefaultProps` has been implemented) will help alleviate some of the complexity of the current solution in 1.1.~~

~~I think we've got some good mechanisms/ideas in play for removing some of our code, but ultimately stripping those `import` statements out would be ideal, as compared with letting them exist and import no-ops/nothing at all, so there's room to improve upon that. I've started investigating just how difficult (or not) it would be to write a Babel transform/plugin to do this work for us, and I think we can get there over time but since it'll be our first stab at authoring something like that, it won't be an immediately available path (unless somebody more experienced with the Babel API steps in to help).~~

~~Let me do some additional research on the build time impact and some other items and we can strategize on the best path forward from here.~~

Nm, your approach makes sense, and is way better than the mess I set up. Carry on

**Comment by dhedgecock** [comment]
We talked it over and have decided on the following:
1. Lock down the prop-types version imported in package.json.
2. Maintain in repo production shims pulled directly from the prop-types repo.
3. Validate that our prod shims are still 👍 any time we bump the prop-types version in package.

This should:
1. Ensure our production validator shims are never out of sync with library validators
2. Have little to no impact on build times as our shims are not minified.
3. Reduce prod shim weight to a measly peasly little 0.12KB gzipped.

As noted in the prod shims, if some totally rad dev writes a babel plugin to strip out the propTypes declarations and import statements we can stop importing the production shims entirely.

Feels good with you @evrowe ?

**Comment by evrowe** [comment]
Feels oh so good, @DHedgecock

**Review by evrowe — APPROVED** [review]

**Pull request merged**
