### PR TITLE
Use babel inline-replace-variables plugin

### PR DESCRIPTION
**Pull request by bigmoves**
Addresses #7

### CODE REVIEW

**Comment by dhedgecock** [comment]
WOOP WOOP WOOP 🎆 

How can we add the plugin in a way that checks if the consuming app or some other addon (Radical) has already added the plugin, and if so updates the config with our vars?

**Comment by bigmoves** [comment]
@DHedgecock the plugin only runs on the addon tree so none of the variables are going to overlap. I believe that options object is only for the addon build so if another addon does the same thing we're not going to clobber their config. Also you can't access the `NODE_ENV` we're defining for the addon in a consuming app because they are transpiled separately so we should be okay?

**Comment by dhedgecock** [comment]
If the plugin only runs on the addon tree, we're good. 👍

**Review by dhedgecock — APPROVED** [review]

**Review by evrowe — APPROVED** [review]
Yeah that's real nice

**Pull request merged**
